[build-system]
requires = ["pbr>=6.1.1"]
build-backend = "pbr.build"

[project]
name = "reno"
description = "Release Notes Manager."
authors = [
    {name = "OpenStack", email = "openstack-discuss@lists.openstack.org"},
]
readme = {file = "README.rst", content-type = "text/x-rst"}
license = "Apache-2.0"
dynamic = ["version", "dependencies"]
requires-python = ">=3.11"
classifiers = [
    "Environment :: OpenStack",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Typing :: Typed",
]

[dependency-groups]
typing = [
    "mypy",
    "types-docutils",
    "types-PyYAML",
]

[project.urls]
Homepage = "https://docs.openstack.org/reno"
Repository = "https://opendev.org/openstack/reno"

[project.optional-dependencies]
sphinx = [
    "sphinx>=5.0.0", # BSD
]

[project.entry-points."distutils.commands"]
"build_reno" = "reno.setup_command:BuildReno"

[project.scripts]
reno = "reno.main:main"

[tool.setuptools.packages.find]
include = ["reno*"]

[tool.mypy]
python_version = "3.11"
show_column_numbers = true
show_error_context = true
strict = true
disable_error_code = ["import-untyped"]
exclude = "(?x)(doc | releasenotes)"

[[tool.mypy.overrides]]
module = ["reno.tests.*"]
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_subclassing_any = false

[[tool.mypy.overrides]]
module = ["sphinx.*"]
follow_imports = "skip"

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "preserve"
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "RUF", "S", "UP", "W"]
ignore = [
    # there are a lot of these to fix
    "RUF012",
    "UP031",
    # we only use asserts for type narrowing
    "S101",
    "S311",
    "S603",
]
external = ["H"]
