sections:
  - [features, New Features]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes]
  - [deprecations, Deprecation Notes]
  - [critical, Critical Issues]
  - [security, Security Issues]
  - [fixes, Bug Fixes]
  - [fixes_command_line, Command Line, 2]
  - [other, Other Notes]
